### ISSUE TITLE
在function中使用field时，子组件ui层无法更新

### ISSUE THREAD

**Issue by chipssss** [alibaba-fusion/field#17]
前端新手，最近使用field进行组件开发遇到以下问题，望解答，谢谢🙏。
在function中使用field时，子组件ui层无法更新（输入/编辑视图没反应，卡住的感觉），getValue能够取值输入的第一个字段，代码如下：

——————————
import React, {useState} from 'react';
import {Field, Input} from '@alifd/next'
export default function TestField(props) {
  let field = new Field(this);
  let init = field.init;

  const onClick = () => {
    console.debug('value',field.getValue('input'))
  };

  return (
    <div>
    <Input {...init('input')}/>
      <button onClick={onClick}>click</button>
    </div>
  );
}
——————————
ui， 连续输入f，但ui没有更新：
![image](https://user-images.githubusercontent.com/39876165/63329598-d4739000-c364-11e9-8613-23d315118f10.png)
连续输入f，多次点击按钮，控制台输出：
![image](https://user-images.githubusercontent.com/39876165/63329658-f0773180-c364-11e9-9a98-30c1a3313a03.png)
去掉init后正常

**Comment by jdkahn** [comment]
You cannot use `new Field(this)` inside a functional component. You must use React Hooks, which will be supported in an upcoming release.

**Comment by chipssss** [comment]
> You cannot use `new Field(this)` inside a functional component. You must use React Hooks, which will be supported in an upcoming release.

thanks！
